name: Conftest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conftest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conftest
        run: |
          LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
          wget "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz"
          tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin
      
      - name: Change directories to rego policy
        run: git clone https://github.com/sn0rlaxlife/terraform-aks-azure.git
      - name: Conftest Action
        # You may pin to the exact commit or the version.
        # uses: YubicoLabs/action-conftest@45941ed2fdf1f97fc2d3b4afbeb39cd40a5d8993
        uses: YubicoLabs/action-conftest@v3
        with:
        # Files and/or folders for Conftest to test (space delimited)
          files: 
            https://github.com/sn0rlaxlife/terraform-aks-azure
          policy: /policies/aks_best_practices.rego
          # Files or folder with supplemental test data
          pull-url: https://github.com/sn0rlaxlife/terraform-aks-azure.git
