name: Conftest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conftest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conftest
        run: |
          curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_${{ runner.os }}_amd64.tar.gz
          tar xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run conftest
        run: conftest test --policy aks_best_practices.rego pwd /policies/
